# Generated by Django 5.2.8 on 2025-11-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='User profile image', null=True, upload_to='images'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
